### ISSUE TITLE
Use LTS versions of binaries instead of latests?

### ISSUE THREAD

**Issue by cyrille-leclerc** [cloudbees/java-build-tools-dockerfile#13]
Shall we use LTS versions of executable instead of latest?
- Firefox ESR for better compatibility with Selenium
  - https://launchpad.net/~team-esr/+archive/ubuntu/firefox-esr
  - Seem complex to instal
  - Another approach is to keep selenium-server-standalone to the latest version
- JDK
- Shall we also use an Ubuntu LTS

**Comment by cyrille-leclerc** [comment]
cc @ydubreuil @ndeloof @michaelneale

**Comment by Vlatombe** [comment]
http://sourcedigit.com/15963-how-to-install-firefox-38-on-32-bit64-bit-ubuntu-15-04-ubuntu-14-10-and-ubuntu-14-04/

**Comment by ndeloof** [comment]
docker image "ubuntu:latest" actually is the LTS. "latest" in docker ecosystem is totally different meaning than in java/maven world where is means "last snapshot"

We also could just rely on java:8 official image (based on debian) so we don't have to care about this.

**Comment by ydubreuil** [comment]
Firefox is a fast moving target. I agree that sticking to ESR will ensure that Selenium is compatible but on the other hand, testing against latest web browser version is important too.

To ensure that selenium always works, you could also lock down the installed Firefox version with the right `apt` argument.

**Comment by cyrille-leclerc** [comment]
The Firefox version is specified as we have to download the binaries for the install.
For the JDK, we will continue to rely on `apt-get`.

We bumped Ubuntu to 16.04 / LTS.
