### ISSUE TITLE
`/tmp/` does not seem to be writable

### ISSUE THREAD

**Issue by cyrille-leclerc** [cloudbees/java-build-tools-dockerfile#16]
The Jenkins Config File Provider fail to create file when targetLocation is not specified

**Comment by cyrille-leclerc** [comment]
cc @ndeloof

**Comment by ndeloof** [comment]
I just checked - `/tmp` is writable in docker image.
Need to run a test instance to diagnose this issue with Config File Provider

**Comment by cyrille-leclerc** [comment]
I'll provide a testcase
