### ISSUE TITLE
Include Gradle build system

### ISSUE THREAD

**Issue by cosmocracy** [cloudbees/java-build-tools-dockerfile#33]
To quote the [Gradle](https://gradle.org/getting-started-gradle/) documentation, it is "an open-source build automation tool for the Age of Continuous Delivery (CD)."  Gradle offers significant improvements over Maven in terms of simplicity, performance, and overall developer experience.

See https://hub.docker.com/r/niaquinto/gradle/ for an image focused specifically on Gradle.

**Comment by ieugen** [comment]
I've opened https://github.com/cloudbees/jnlp-slave-with-java-build-tools-dockerfile/issues/13 but I think it's better suited here.
