### ISSUE TITLE
include JSON processor tool (like jq)

### ISSUE THREAD

**Issue by cs-mahmoud-khateeb** [cloudbees/java-build-tools-dockerfile#36]
it would be handy to have a JSON processor in this image, I would vote for [jq](https://stedolan.github.io/jq/)

I am happy to raise a PR if that's acceptable.

**Comment by cyrille-leclerc** [comment]
Can you please test `cloudbees/java-build-tools:latest`?

See https://github.com/cloudbees/java-build-tools-dockerfile/commit/593c533d274d5b31c8bf32b3314085b6af0c02f8

**Comment by cs-mahmoud-khateeb** [comment]
working fine. thanks!

**Comment by cyrille-leclerc** [comment]
You're welcome @cs-mahmoud-khateeb
