### ISSUE TITLE
Java 8 is oldish ... Let's switch to Java 11 !!

### ISSUE THREAD

**Issue by aheritier** [cloudbees/java-build-tools-dockerfile#42]
Java 8 is EOL, Java 11 is out ...

**Comment by jhovell** [comment]
Is there any roadmap on this upgrade? Is this image still being maintained? Haven't seen any activity in last 6 months...

**Comment by cyrille-leclerc** [comment]
This image is still maintained @jhovell . We did not bump to Java 11 because Java 8 is still the mostly used JVM when using Jenkins.

**Comment by richbg** [comment]
Java 8 is still the mostly used JVM when using Jenkins.
