### ISSUE TITLE
RFE: use java-build-tools image as image for the jenkins docker plugin

### ISSUE THREAD

**Issue by cyrille-leclerc** [cloudbees/java-build-tools-dockerfile#5]
The [Jenkins Docker Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Docker+Plugin) should be able to use the java-build-tools image to provision build slaves

**Comment by ndeloof** [comment]
not possible with Jenkins Docker Plugin, which has some specific pre-requisites on the image being used. Better to use with oki-docki or [container-slaves-plugin](https://github.com/ndeloof/container-slaves-plugin)

**Comment by cyrille-leclerc** [comment]
@ndeloof does it mean that we should publish another image? Something like "docker-slave"?

**Comment by cyrille-leclerc** [comment]
Done with https://github.com/cloudbees/jnlp-slave-with-java-build-tools-dockerfile
